// Generated by CoffeeScript 1.8.0
(function() {
  var JsonSearch;

  JsonSearch = {
    levels: [],
    depth: function() {
      return this.levels.length;
    },
    clear: function() {
      return this.levels = [];
    },
    _json_merge: function(base, to_merge) {
      var k, v;
      if (base === void 0) {
        base = {};
      }
      console.log(to_merge);
      for (k in to_merge) {
        v = to_merge[k];
        if (!base[k]) {
          base[k] = v;
        }
        console.log("value = " + v + " , base[k]= " + base[k]);
      }
      return base;
    },
    read: function(json) {
      return this.read_level(0, json);
    },
    read_level: function(lvl, json) {
      var k, new_json, v;
      new_json = {};
      for (k in json) {
        v = json[k];
        if (typeOf(v) === Object) {
          this.read_level(lvl + 1, v);
        }
        new_json[k] = typeOf(v);
      }
      return this.levels[lvl] = this._json_merge(this.levels[lvl], new_json);
    }
  };

  window.JsonSearch = JsonSearch;

}).call(this);
