// Generated by CoffeeScript 1.8.0
(function() {
  var class2type, type2Object, typeOf, types;

  class2type = {};

  type2Object = {};

  types = [[Boolean, "Boolean"], [Number, "Number"], [String, "String"], [Function, "Function"], [Array, "Array"], [Date, "Date"], [RegExp, "RegExp"], [Object, "Object"], [Error, "Error"]];

  types.forEach(function(name, i) {
    class2type["[object " + name[1] + "]"] = name[0];
    return type2Object[name[1].toLowerCase()] = name[0];
  });

  typeOf = function(obj) {
    if (obj === null) {
      return obj + "";
    }
    if (typeof obj === "object" || typeof obj === "function") {
      return class2type[toString.call(obj)] || Object;
    } else {
      return type2Object[typeof obj] || typeof obj;
    }
  };

  window.typeOf = typeOf;

}).call(this);
